# Generated by Django 5.1.2 on 2024-10-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_product_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store_custo_last_na_2e448d_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
