# Generated by Django 5.1.2 on 2024-10-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0003_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_2e448d_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
