# Generated by Django 5.1.2 on 2024-10-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_remove_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
