# Generated by Django 5.1.3 on 2024-11-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0012_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
